theme: jekyll-theme-minimal
title: Tugba's Progress Journal
description: MEF BDA 503 Fall 2020-2021
description: you can see my project group progress journal [here](https://pjournal.github.io/mef04g-madagaskar/)
